defaults:
    - agent: wcsac_pricing
    - _self_

env: preemptive_pricing
experiment: pricing_exp

excessive_capacity_npz: ../../wc_sac/dataset/excessive_capacity_cpu_300sec_azure.npz
p_min: 0.1
p_max: 1.0
dt: 300.0
horizon: 288
n0: 0.0
eta: 0.33
thet: 0.33
k: 2.0
omega: 2.4
price_level_min: 0.1
price_level_max: 1.0
price_level_step: 0.1

num_train_steps: 300000
replay_buffer_capacity: 1000000
num_seed_steps: 5000
eval_frequency: 20000
num_eval_episodes: 10

device: cpu
log_frequency: 10000
log_save_tb: true

seed: 1
risk_level: 0.5
restart_path: dummy
